# Generated by Django 3.2.4 on 2021-09-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Student Tech Team'), (3, '3D Printer Status')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Off'), (1, 'On'), (2, 'Flashing')], default=0)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Warning'), (2, 'Critical')], default=0)),
                ('message', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Daily Slide')], default=0)),
                ('reason', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('path', models.FileField(upload_to='slides/')),
            ],
        ),
    ]
