# Generated by Django 3.2.4 on 2021-09-24 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_name_slide_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagenotice',
            options={'verbose_name': 'Feedback'},
        ),
        migrations.AddField(
            model_name='slide',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
