# Generated by Django 3.2.4 on 2021-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.IntegerField(choices=[(0, 'Other'), (1, 'SCPS A/B Day Calendar'), (2, 'SCPS Instructional Calendar')], default=0)),
                ('calendar_id', models.CharField(max_length=255)),
            ],
        ),
    ]
