# Generated by Django 3.2.4 on 2021-10-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_calendar_schedulecalendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulecalendar',
            options={'verbose_name': 'Schedule Calendar'},
        ),
    ]
