# Generated by Django 3.2.4 on 2021-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedulecalendar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPIServiceJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='/service/')),
            ],
            options={
                'verbose_name': 'Google API Service JSON',
            },
        ),
    ]
