# Generated by Django 3.2.4 on 2022-01-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_googleapiservicejson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapiservicejson',
            name='file',
            field=models.FileField(upload_to='service/'),
        ),
    ]
